/*
# Add Zoom link and email integration fields

## Overview
This migration adds:
1. A `zoom_link` column to the `bookings` table so that Zoom meeting join links
   generated by the edge function can be stored on each booking.
2. Two new columns to `admin_settings`:
   - `email_from_name` — the display name used as the "From" name in outgoing emails
   - `zoom_enabled` — a global toggle to enable/disable automatic Zoom meeting creation

## Modified Tables

### bookings (new column)
- zoom_link (text, nullable) — stores the Zoom join URL for the meeting, if one
  was created. Null means no Zoom meeting was created for this booking.

### admin_settings (new columns)
- email_from_name (text, default 'Jungo Solutions') — the sender display name
  used in the "From" header of outgoing booking emails
- zoom_enabled (boolean, default false) — when true, the system will attempt to
  create a Zoom meeting for each booking via the Zoom Server-to-Server OAuth app

## Security
No new tables. Existing RLS policies on bookings and admin_settings already
cover the new columns — no policy changes needed.
*/

-- Add zoom_link to bookings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'zoom_link') THEN
    ALTER TABLE bookings ADD COLUMN zoom_link text;
  END IF;
END $$;

-- Add email_from_name to admin_settings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'admin_settings' AND column_name = 'email_from_name') THEN
    ALTER TABLE admin_settings ADD COLUMN email_from_name text NOT NULL DEFAULT 'Jungo Solutions';
  END IF;
END $$;

-- Add zoom_enabled to admin_settings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'admin_settings' AND column_name = 'zoom_enabled') THEN
    ALTER TABLE admin_settings ADD COLUMN zoom_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;
